### PR TITLE
SpringBoot 2.0

### PR DESCRIPTION
**Pull request by humbertodias**
Upgrading SpringBoot version to 2.0.0.RELEASE
Fixing CORS

### CODE REVIEW

**Comment by mevdschee** [comment]
Awesome!! I will revert your changed config, but other than that it is very useful! I do want to merge your contribution, but only if you are okay with the MIT licensing, are you?

**Comment by humbertodias** [comment]
Hi
No problem, go ahead.
Thanks.

**Comment by humbertodias** [comment]
Adding Swagger Support  …
- API Descriptor http://localhost:8080/v2/api-docs
- Swagger UI http://localhost:8080/swagger-ui.html

chrome_2018-03-12_11-28-09

**Comment by mevdschee** [comment]
I merged and tried this out, but the (generated) swagger output it not (yet) good enough for real world usage.

**Pull request merged**
